//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSRCmdGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPSRCmdGen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Category I
        ///; grammar tier Easy
        ///
        ///$Main	= $complex 
        ///
        ///$complex	= $simple and $simple
        ///$complex	= $getobj and $deliver
        ///$complex	= $findprs and $answer
        ///
        ///$getobj		= 
        ///
        ///$deliver	=
        ///
        ///$findprs	=
        ///
        ///$answer		=.
        /// </summary>
        internal static string Category1Grammar {
            get {
                return ResourceManager.GetString("Category1Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Category2Grammar {
            get {
                return ResourceManager.GetString("Category2Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Category3Grammar {
            get {
                return ResourceManager.GetString("Category3Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Count
        ///; grammar tier High
        ///
        ///$Main   = $count
        ///$count  = $count1 | $count2 | $count3
        ///
        ///$count1 = count the $cntxat $report
        ///$cntxat = $cntoat | $cntpat
        ///$cntoat = $object at the {placement 1}
        ///$cntpat = $people at the {room 1}
        ///
        ///$count2 = $navigt $docntx $report 
        ///$navigt = $goverb to the 
        ///$docntx = $docnto | $docntp
        ///$docnto = {placement 2}, count the $object
        ///$docntp = {room 2}, count the $people
        /// 
        ///$count3 = Tell $target how many $ctable
        ///$ctable = $objain | $pplain
        ///$objain = $object are in the {placem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountGrammar {
            get {
                return ResourceManager.GetString("CountGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*****************************************************************************
        ///*
        ///* FORMAT
        ///*
        ///******************************************************************************
        ///*
        ///* ROOT
        ///* The root rule S of the grammar is the $Main Non-Terminal. In order for the
        ///* grammar to be valid, it must contain at least one $Main rule.
        ///*
        ///* Non-Terminal identifiers
        ///* A valid Non-Terminal identifier is a sequence of one or more letters,
        ///* digits, or underscore characters (_). Spaces, punctuation marks, and symbols
        ///* cannot be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormatSpecification {
            get {
                return ResourceManager.GetString("FormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##############################################################################
        ///#
        ///# ${GrammarName} Grammar
        ///# 
        ///# Author:  Mauricio Matamoros
        ///# Date:    March 2015
        ///#
        ///# IMPORTANT: 
        ///# Since this document declares a grammar for generating sentences,
        ///# NO RECURSIVE rules must be used.
        ///# 
        ///##############################################################################
        ///.
        /// </summary>
        internal static string GrammarHeader {
            get {
                return ResourceManager.GetString("GrammarHeader", resourceCulture);
            }
        }
    }
}
