//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboCup.AtHome.EEGPSRCmdGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoboCup.AtHome.EEGPSRCmdGen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Cat1 - Advanced Manipulation
        ///; grammar tier High
        ///
        ///$Main     = $advman
        ///
        ///##############################################################################
        ///#
        ///# Serving breakfast
        ///#
        ///##############################################################################
        ///
        ///$advman   = $polite bring me something for breakfast; Up to the team to solve
        ///$advman   = $polite serve the breakfast; Up to the team how to solve
        ///$advman   = $polite bring me some $cereal, $fuit and $drink in a tray
        ///
        ///
        ///######## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEGPSR_Category1 {
            get {
                return ResourceManager.GetString("EEGPSR_Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Cat2 - Advanced Object Recognition
        ///; grammar tier High
        ///
        ///$Main = $advor
        ///
        ///##############################################################################
        ///#
        ///# Bring from description
        ///#
        ///##############################################################################
        ///$advor	= $polite bring me the $bwhat from the {placement 1}.
        ///$advor	= $polite take the $bwhat from the {placement 1} to the {placement 2}.
        ///$advor	= $polite bring me the {category} at the $rpos {placement 1}.
        ///$advor	= Take the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEGPSR_Category2 {
            get {
                return ResourceManager.GetString("EEGPSR_Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Cat3 - HRI and Incomplete Commands
        ///; grammar tier High
        ///
        ///$Main     = $polite $command
        ///
        ///##############################################################################
        ///#
        ///# Complex commands
        ///#
        ///##############################################################################
        ///$command  = $followob
        ///$command  = $guideob
        ///$command  = $findorob
        ///$command  = $findmpob and $guidem
        ///$command  = $findfpob and $guidef
        ///
        ///$command  = $takeob and ($place | $deliver)
        ///$command  = $take and ($placeob | $ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEGPSR_Category3 {
            get {
                return ResourceManager.GetString("EEGPSR_Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Cat4 - Memory and Awareness
        ///; grammar tier High
        ///
        ///$Main = $disclaimer
        ///
        ///
        ///##############################################################################
        ///#
        ///# Polite
        ///#
        ///##############################################################################
        ///$polite = $disclaimer 
        ///$polite = $disclaimer Please
        ///$polite = $disclaimer Could you
        ///$polite = $disclaimer Robot please
        ///$polite = $disclaimer Could you please
        ///
        ///##############################################################################        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEGPSR_Category4 {
            get {
                return ResourceManager.GetString("EEGPSR_Category4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Cat5 - People Recognition and Navigation
        ///; grammar tier High
        /// 
        ///$Main = $advprn
        ///
        ///##############################################################################
        ///#
        ///# Greet person matching description
        ///#
        ///##############################################################################
        ///$advprn	= $polite greet the $gwho
        ///$advprn	= $polite kill the $gwho
        ///
        ///$gwho	= $person in the $room
        ///
        ///##############################################################################
        ///#
        ///# Bring to person match [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEGPSR_Category5 {
            get {
                return ResourceManager.GetString("EEGPSR_Category5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; grammar name Cat6 - Simple Tasks
        ///; grammar tier Moderate
        ///
        ///$Main     = $polite $complex.
        ///
        ///
        ///##############################################################################
        ///#
        ///# Complex commands
        ///#
        ///##############################################################################
        ///$complex  = $triple
        ///$complex  = $single, $single, and $single
        ///$complex  = $doublel, and $single
        ///$complex  = $single, $doubler
        ///
        ///##############################################################################
        ///#
        ///# Triple task [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EEGPSR_Category6 {
            get {
                return ResourceManager.GetString("EEGPSR_Category6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*****************************************************************************
        ///*
        ///* FORMAT
        ///*
        ///******************************************************************************
        ///*
        ///* ROOT
        ///* The root rule S of the grammar is the $Main Non-Terminal. In order for the
        ///* grammar to be valid, it must contain at least one $Main rule.
        ///*
        ///* Non-Terminal identifiers
        ///* A valid Non-Terminal identifier is a sequence of one or more letters,
        ///* digits, or underscore characters (_). Spaces, punctuation marks, and symbols [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FormatSpecification {
            get {
                return ResourceManager.GetString("FormatSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##############################################################################
        ///#
        ///# ${GrammarName} Grammar
        ///# 
        ///# Author:  Mauricio Matamoros
        ///# Date:    June 2016
        ///#
        ///# IMPORTANT: 
        ///# Since this document declares a grammar for generating sentences,
        ///# NO RECURSIVE rules must be used.
        ///# 
        ///##############################################################################
        ///.
        /// </summary>
        internal static string GrammarHeader {
            get {
                return ResourceManager.GetString("GrammarHeader", resourceCulture);
            }
		}

		internal static string Gestures {
			get {
				return ResourceManager.GetString("Gestures", resourceCulture);
			}
		}

		internal static string Locations {
			get {
				return ResourceManager.GetString("Locations", resourceCulture);
			}
		}

		internal static string Names {
			get {
				return ResourceManager.GetString("Names", resourceCulture);
			}
		}

		internal static string Objects {
			get {
				return ResourceManager.GetString("Objects", resourceCulture);
			}
		}

		internal static string Questions {
			get {
				return ResourceManager.GetString("Questions", resourceCulture);
			}
		}
    }
}
